import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useCart } from '../context/CartContext.jsx';

export default function Cart() {
  const { cart, subtotal, shipping, total, updateQuantity, removeFromCart } = useCart();
  const navigate = useNavigate();
  if (!cart.items.length) return <div className="page-center"><div className="empty-icon"><ShoppingBag /></div><h2>Your cart is empty</h2><p>Add something you like and come back here.</p><Link className="btn btn-primary" to="/products">Start shopping <ArrowRight size={18} /></Link></div>;
  return <div className="container page-content"><div className="section-title"><span className="eyebrow">Shopping cart</span><h1>Your selected items</h1></div><div className="cart-layout"><div className="cart-list">{cart.items.map(item => <div className="cart-item" key={item.product._id}><img src={item.product.image} alt={item.product.title} /><div className="cart-info"><Link to={`/products/${item.product._id}`}><h3>{item.product.title}</h3></Link><span>{item.product.brand}</span><strong>₹{item.product.price.toLocaleString('en-IN')}</strong></div><div className="qty"><button disabled={item.quantity === 1} onClick={() => updateQuantity(item.product._id, item.quantity - 1)}><Minus size={15} /></button><span>{item.quantity}</span><button disabled={item.quantity >= item.product.stock} onClick={() => updateQuantity(item.product._id, item.quantity + 1)}><Plus size={15} /></button></div><strong className="line-total">₹{(item.product.price * item.quantity).toLocaleString('en-IN')}</strong><button className="delete-btn" onClick={() => removeFromCart(item.product._id)}><Trash2 size={18} /></button></div>)}</div><aside className="summary"><h3>Order summary</h3><div><span>Subtotal</span><strong>₹{subtotal.toLocaleString('en-IN')}</strong></div><div><span>Shipping</span><strong>{shipping ? `₹${shipping}` : 'FREE'}</strong></div><div className="summary-total"><span>Total</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><button className="btn btn-primary full" onClick={() => navigate('/checkout')}>Proceed to checkout <ArrowRight size={18} /></button>{shipping > 0 && <small>Add ₹{(999 - subtotal).toLocaleString('en-IN')} more for free shipping.</small>}</aside></div></div>;
}
